---
# tasks file for phpmyadmin
- name: create phpmyadmin directory
  file:
    path: "{{ phpmyadmin_httpd_directory[ansible_distribution] }}/phpmyadmin"
    state: directory
    owner: "{{ phpmyadmin_httpd_user[ansible_distribution] }}"
    group: "{{ phpmyadmin_httpd_group[ansible_distribution] }}"
    mode: 0750

- name: download software
  get_url:
    url: "{{ phpmyadmin_targz }}"
    dest: /tmp/phpmyadmin.zip

- name: unpack software
  unarchive:
    src: /tmp/phpmyadmin.zip
    dest: /tmp/phpmyadmin

- name: install software
  copy:
    src: /tmp/phpmyadmin/?/*
    dest: "{{ phpmyadmin_httpd_directory[ansible_distribution] }}/phpmyadmin"
    remote_src: yes

- name: configure software
  template:
    src: templates/config.inc.php.j2
    dest: "{{ phpmyadmin_httpd_directory[ansible_distribution] }}/phpmyadmin/config.inc.php"
    owner: "{{ phpmyadmin_httpd_user[ansible_distribution] }}"
    group: "{{ phpmyadmin_httpd_group[ansible_distribution] }}"
    mode: 0640
