---
# tasks file for phpmyadmin
- name: create directories
  file:
    path: "{{ phpmyadmin_httpd_directory[ansible_distribution] }}/phpmyadmin"
    state: directory
    owner: "{{ phpmyadmin_httpd_user[ansible_distribution] }}"
    group: "{{ phpmyadmin_httpd_group[ansible_distribution] }}"
    mode: 0750
  with_items:
    - "{{ phpmyadmin_httpd_directory[ansible_distribution] }}/phpmyadmin"
    - "{{ phpmyadmin_tmp_directory }}"

- name: download and unpack software
  unarchive:
    src: "{{ phpmyadmin_zip }}"
    dest: "{{ phpmyadmin_tmp_directory }}"
    remote_src: yes

- name: install software
  copy:
    src: "{{ phpmyadmin_tmp_directory }}/{{ phpmyadmin_unpack_directory }}"
    dest: "{{ phpmyadmin_httpd_directory[ansible_distribution] }}/phpmyadmin"
    remote_src: yes

- name: configure software
  template:
    src: templates/config.inc.php.j2
    dest: "{{ phpmyadmin_httpd_directory[ansible_distribution] }}/phpmyadmin/config.inc.php"
    owner: "{{ phpmyadmin_httpd_user[ansible_distribution] }}"
    group: "{{ phpmyadmin_httpd_group[ansible_distribution] }}"
    mode: 0640
