---
# tasks file for phpmyadmin
- name: create directory
  file:
    path: "{{ phpmyadmin_httpd_directory[ansible_distribution] }}/phpmyadmin"
    state: directory
    owner: "{{ phpmyadmin_httpd_user[ansible_distribution] }}"
    group: "{{ phpmyadmin_httpd_group[ansible_distribution] }}"
    mode: 0750

- name: download and unpack software
  unarchive:
    src: "{{ phpmyadmin_archive }}"
    dest: "{{ phpmyadmin_httpd_directory[ansible_distribution] }}/phpmyadmin/"
    remote_src: true
    extra_opts: ['--strip-components=1']

- name: configure software
  template:
    src: templates/config.inc.php.j2
    dest: "{{ phpmyadmin_httpd_directory[ansible_distribution] }}/phpmyadmin/config.inc.php"
    owner: "{{ phpmyadmin_httpd_user[ansible_distribution] }}"
    group: "{{ phpmyadmin_httpd_group[ansible_distribution] }}"
    mode: 0640

- name: install requirements
  package:
    name: "{{ item }}"
  with_items:
    - "{{ phpmyadmin_requirements[ansible_distribution ~ '-' ~ ansible_distribution_major_version]
      | default(phpmyadmin_requirements[ansible_distribution]
      | default(phpmyadmin_requirements['default'] )) }}"

- name: configure httpd
  template:
    src: templates/phpmyadmin.conf.j2
    dest: "{{ phpnmyadmin_httpd_conf_directory[ansible_distribution] }}/phpmyadmin.conf"
  notify:
    - restart httpd
