---
# tasks file for phpmyadmin

- name: include assert.yml
  import_tasks: assert.yml
  run_once: yes
  delegate_to: localhost

- name: install requirements
  package:
    name: "{{ phpmyadmin_requirements }}"
    state: present
  notify:
    - restart httpd

- name: modify selinux settings
  seboolean:
    name: httpd_unified
    state: yes
    persistent: yes
  when:
    - ansible_selinux.status is defined
    - ansible_selinux.status == "enabled"

- name: create directory
  file:
    path: "{{ phpmyadmin_httpd_directory }}/phpmyadmin"
    state: directory
    owner: "{{ phpmyadmin_httpd_user }}"
    group: "{{ phpmyadmin_httpd_group }}"
    mode: "755"

- name: download and unpack software
  unarchive:
    src: "{{ phpmyadmin_archive }}"
    dest: "{{ phpmyadmin_httpd_directory }}/phpmyadmin/"
    remote_src: yes
    extra_opts: ['--strip-components=1']
    mode: "0755"

- name: create directories
  file:
    path: "{{ phpmyadmin_httpd_directory }}/phpmyadmin/tmp"
    state: directory
    owner: "{{ phpmyadmin_httpd_user }}"
    group: "{{ phpmyadmin_httpd_group }}"
    mode: "0750"

- name: configure software
  template:
    src: config.inc.php.j2
    dest: "{{ phpmyadmin_httpd_directory }}/phpmyadmin/config.inc.php"
    owner: "{{ phpmyadmin_httpd_user }}"
    group: "{{ phpmyadmin_httpd_group }}"
    mode: "640"
