---
- name: Converge
  hosts: all
  gather_facts: no
  become: yes

  vars:
    python_pip_modules:
      - name: pyopenssl

  roles:
    - robertdebock.bootstrap
    - robertdebock.buildtools
    - robertdebock.epel
    - robertdebock.python_pip
    - robertdebock.httpd
    - robertdebock.php
    - robertdebock.mysql
    - ansible-role-phpmyadmin
