---
- name: Prepare
  hosts: all
  gather_facts: no
  become: yes

  roles:
    - role: robertdebock.bootstrap
    - role: robertdebock.buildtools
    - role: robertdebock.epel
    - role: robertdebock.python_pip
      python_pip_modules:
        - name: pyopenssl
    - role: robertdebock.httpd
    - role: robertdebock.mysql
    - role: robertdebock.remi
      remi_enabled_repositories:
        - php73
    - role: robertdebock.php
