---
# handlers file for phpmyadmin
- name: restart httpd
  service:
    name: "{{ item }}"
    state: restarted
  when:
    - ansible_virtualization_type != "docker"
  with_items:
    - "{{ phpmyadmin_httpd_services[ansible_distribution ~ '-' ~ ansible_distribution_major_version]
      | default(phpmyadmin_httpd_services[ansible_distribution]
      | default(phpmyadmin_httpd_services['default'] )) }}"
