---
# vars file for phpmyadmin
phpmyadmin_archive: https://files.phpmyadmin.net/phpMyAdmin/{{ phpmyadmin_version }}/phpMyAdmin-{{ phpmyadmin_version }}-all-languages.tar.gz

phpmyadmin_requirements:
  - php-mysql
  - php-mbstring
  - php-pecl-zip

phpmyadmin_httpd_directory: /var/www/html

phpmyadmin_httpd_user: apache

phpmyadmin_httpd_group: apache
