---
- name: Converge
  hosts: all
  gather_facts: "no"
  strategy: free

  roles:
    - role: robertdebock.bootstrap
    - role: robertdebock.buildtools
    - role: robertdebock.epel
    - role: robertdebock.scl
    - role: robertdebock.python-pip
      python_pip_modules:
        - name: pyopenssl
    - role: robertdebock.httpd
    - role: robertdebock.php
    - role: robertdebock.mysql
    - role: ansible-role-phpmyadmin
