---
- name: Verify
  hosts: all
  become: yes
  gather_facts: no

  tasks:
    - name: Check if phpmyadmin can be reached
      uri:
        url: "http://localhost/phpmyadmin/"
        status_code: 200
