---
- name: Verify
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: Check if phpmyadmin can be reached
      uri:
        url: "http://localhost/phpmyadmin/"
        status_code: 200
