---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: phpmyadmin-debian-sid
    image: debian:sid
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: debian-sid
verifier:
  name: goss
  lint:
    name: yamllint
